# Generated by Django 3.0.5 on 2020-04-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planner', '0002_auto_20200422_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity_owned',
            field=models.IntegerField(default=0),
        ),
    ]
