# Generated by Django 3.1.2 on 2022-05-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planner', '0003_auto_20200423_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='quantity_owned',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
    ]
