# Generated by Django 3.1.2 on 2022-05-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planner', '0004_funds_quantity_owned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funds',
            old_name='type',
            new_name='symbol',
        ),
    ]
